apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

patches:
  - target:
      kind: Service
      name: devops-microservice
    patch: |
      - op: replace
        path: /spec/type
        value: ClusterIP

images:
  - name: PLACEHOLDER/devops-microservice
    newName: acrdevopsp5dvy7.azurecr.io/devops-microservice
    newTag: develop-a8de34821a88179ac4c575b58724e09b70121fb0
