apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-dev

resources:
  - ../../base
  - namespace.yaml


images:
  - name: PLACEHOLDER/devops-microservice
    newName: acrdevopsp5dvy7.azurecr.io/devops-microservice
    newTag: manual-test
